version: "3"

services:
  nginx:
    container_name: myproxy
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - html:/usr/share/nginx/html/
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app1:
    container_name: app1
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5001:3000"
    depends_on:
      - db
    
  app2:
    container_name: app2
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5002:3000"
    depends_on:
      - db

  app3:
    container_name: app3
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5003:3000"
    depends_on:
      - db
      
volumes:
  db-data:
    driver: local
  html:
    driver: local